// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebibpirgvslojaertdyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViaWJwaXJndnNsb2phZXJ0ZHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzc0ODcsImV4cCI6MjA2Mzc1MzQ4N30.enbRBDlR-jqypYS2egbQdsCmYIvTeDdofAO310LRsGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);